on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: docker
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: apt update && apt install -y cmake
      - run: mkdir -p build
      - run: cd build ; cmake .. ; make -j$(nproc) test
