on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: docker
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: apt update && apt install -y cmake

      - name: Test
        run: mkdir -p build ; cd build ; cmake .. ; make -j$(nproc) test
