on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: docker
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: apt update && DEBIAN_FRONTEND=noninteractive apt-get install -y bash cmake g++ git make libxkbcommon-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev pkg-config libgl-dev

      - name: Test
        run: mkdir -p build ; cd build ; cmake .. ; make -j$(nproc) test
