on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: docker
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: https://github.com/awalsh128/cache-apt-pkgs-action@v1.4.1
        with:
          packages: cmake
          version: 1.0

      - run: mkdir -p build

      - run: cd build ; cmake .. ; make -j$(nproc) test
