on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: birb3d
    container:
      - image: docker:docker://192.168.1.104:5000/toasterbirb/birb3d:latest

    steps:
      - run: git pull
      - name: Test
        run: mkdir -p build ; cd build ; cmake .. ; make -j$(nproc) test
