on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: docker
    container:
      - image: 192.168.1.104:5000/toasterbirb/birb3d:latest
    steps:
      - name: Test
        run: cd Birb3D ; mkdir -p build ; cd build ; cmake .. ; make -j$(nproc) test
