#pragma once

#if MICROPROFILE_ENABLED == 1
#include <microprofile.h>

//////////////////////////
// Microprofile enabled //
//////////////////////////

#define PROFILER_SCOPE_AUDIO(NAME) MICROPROFILE_SCOPEI("Audio", NAME, MP_VIOLETRED);
#define PROFILER_SCOPE_AUDIO_FN() MICROPROFILE_SCOPEI("Audio", __PRETTY_FUNCTION__, MP_VIOLETRED);

#define PROFILER_SCOPE_INPUT(NAME) MICROPROFILE_SCOPEI("Input", NAME, MP_GRAY);
#define PROFILER_SCOPE_INPUT_FN() MICROPROFILE_SCOPEI("Input", __PRETTY_FUNCTION__, MP_GRAY);

#define PROFILER_SCOPE_IO(NAME) MICROPROFILE_SCOPEI("I/O", NAME, MP_LIGHTBLUE);
#define PROFILER_SCOPE_IO_FN() MICROPROFILE_SCOPEI("I/O", __PRETTY_FUNCTION__, MP_LIGHTBLUE);

#define PROFILER_SCOPE_MISC(NAME) MICROPROFILE_SCOPEI("Misc.", NAME, MP_LIGHTYELLOW);
#define PROFILER_SCOPE_MISC_FN() MICROPROFILE_SCOPEI("Misc.", __PRETTY_FUNCTION__, MP_LIGHTYELLOW);

#define PROFILER_SCOPE_PHYSICS(NAME) MICROPROFILE_SCOPEI("Physics", NAME, MP_DARKSLATEBLUE);
#define PROFILER_SCOPE_PHYSICS_FN() MICROPROFILE_SCOPEI("Physics", __PRETTY_FUNCTION__, MP_DARKSLATEBLUE);

#define PROFILER_SCOPE_RENDER(NAME) MICROPROFILE_SCOPEI("Rendering", NAME, MP_LIGHTGREEN);
#define PROFILER_SCOPE_RENDER_FN() MICROPROFILE_SCOPEI("Rendering", __PRETTY_FUNCTION__, MP_LIGHTGREEN);

#else

///////////////////////////
// Microprofile disabled //
///////////////////////////

#define PROFILER_SCOPE_AUDIO(NAME);
#define PROFILER_SCOPE_AUDIO_FN();

#define PROFILER_SCOPE_INPUT(NAME);
#define PROFILER_SCOPE_INPUT_FN();

#define PROFILER_SCOPE_IO(NAME);
#define PROFILER_SCOPE_IO_FN();

#define PROFILER_SCOPE_MISC(NAME);
#define PROFILER_SCOPE_MISC_FN();

#define PROFILER_SCOPE_PHYSICS(NAME);
#define PROFILER_SCOPE_PHYSICS_FN();

#define PROFILER_SCOPE_RENDER(NAME);
#define PROFILER_SCOPE_RENDER_FN();

#endif
