#pragma once
#include <microprofile.h>

#define PROFILER_SCOPE_RENDER(NAME) MICROPROFILE_SCOPEI("Rendering", NAME, MP_LIGHTGREEN);
#define PROFILER_SCOPE_IO(NAME) MICROPROFILE_SCOPEI("I/O", NAME, MP_BLUE);
#define PROFILER_SCOPE_INPUT(NAME) MICROPROFILE_SCOPEI("Input", NAME, MP_GRAY);
