FROM ubuntu:20.04

ARG USER=toasterbirb

# Install all required dependencies
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y bash cmake g++ git make libxkbcommon-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev pkg-config libgl-dev

# Create a new non-root user and set up its workspace
RUN mkdir -p /workspace/${USER}/

# Clone the source code and submodules recursively
RUN git clone --recursive --depth 1 http://192.168.1.104:5000/toasterbirb/Birb3D /workspace/${USER}/Birb3D
