FROM alpine:3.19

ARG USER=user

# Install all required dependencies
RUN apk update && apk add cmake g++ git make doas wayland-dev libxkbcommon-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-dev

# Create a new non-root user and set up its workspace
RUN adduser -D ${USER} &&\
	adduser ${USER} wheel &&\
	chown -R ${USER}:${USER} /home/${USER}

# Configure doas
RUN mkdir -p /etc/doas.d && echo "permit nopass :wheel" > /etc/doas.d/doas.conf

WORKDIR /home/${USER}
USER ${USER}

# Clone the source code and submodules recursively
RUN git clone --recursive --depth 1 http://192.168.1.104:5000/toasterbirb/Birb3D
