FROM alpine:3.19

ARG USER=toasterbirb

# Install all required dependencies
RUN apk update && apk add bash cmake g++ git make doas wayland-dev libxkbcommon-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-dev

# Create a new non-root user and set up its workspace
RUN mkdir -p /workspace/${USER}/

# Configure doas
RUN mkdir -p /etc/doas.d && echo "permit nopass :wheel" > /etc/doas.d/doas.conf

# Create some directory that the forgejo runner expects to find
RUN mkdir -p /var/run

# Clone the source code and submodules recursively
RUN git clone --recursive --depth 1 http://192.168.1.104:5000/toasterbirb/Birb3D /workspace/${USER}/Birb3D
